version: 0.0
os: linux

# Hooks to stop and start the containers th
hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
      # Optionally, pass commit ID to the script
      environment:
        COMMIT_ID: "{{commit_id}}"

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
      # Optionally, pass commit ID to the script
      environment:
        COMMIT_ID: "{{commit_id}}"
